{
 "title": "Local User's Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(baywatch_http_requests_total{handler!=\"/metrics\", handler!=\"/health\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Count by Endpoint Past Hour",
   "type": "bargauge",
   "description": "This query shows the rate of requests per endpoint over the hour.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(handler) (increase(baywatch_http_requests_total{handler!=\"/metrics\", handler!=\"/health\", handler!~\"none\", handler!~\"/openapi.json\"}[1h]))",
     "legendFormat": "{{handler}} {{method}}"
    }
   ]
  },
  {
   "title": "Heart Beat Scrape 15s",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(handler) (baywatch_http_requests_total{handler=\"/metrics\"})",
     "legendFormat": "{{status}} {{handler}} "
    }
   ]
  },
  {
   "title": "Error Rate 500",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(baywatch_http_requests_total{status=~\"5xx\"}[30m])) / sum(rate(baywatch_http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(handler) (baywatch_http_requests_total{handler!=\"/metrics\"})",
     "legendFormat": "{{handler}} {{status}} {{method}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "gauge",
   "description": "Request Duration",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "baywatch_http_request_duration_seconds_sum{handler!=\"none\"} / baywatch_http_request_duration_seconds_count",
     "legendFormat": "{{handler}} {{method}}"
    }
   ]
  },
  {
   "title": "All Request Rate 30 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(baywatch_http_requests_total{handler!=\"/metrics\"}[$__rate_interval])",
     "legendFormat": "{{handler}} {{status}} {{method}}"
    }
   ]
  },
  {
   "title": "Core Request Rate 30min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "baywatch_http_requests_total{handler!=\"/metrics\", handler!=\"/health\"}",
     "legendFormat": "{{method}} - {{status}} - {{handler}}"
    }
   ]
  },
  {
   "title": "Error's In 30 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "baywatch_http_requests_total{status=\"4xx\"}",
     "legendFormat": "{{handler}} {{status}} {{method}}"
    },
    {
     "expr": "baywatch_http_requests_total{status=\"5xx\"}",
     "legendFormat": "{{handler}} {{status}} {{method}}"
    }
   ]
  }
 ]
}